# Generated by Django 3.0.5 on 2020-04-08 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('userid', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('mobilenum', models.BigIntegerField()),
                ('email', models.EmailField(max_length=400)),
                ('gender', models.CharField(max_length=200)),
                ('profile_pic', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Post_Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=2000)),
                ('title', models.CharField(max_length=200)),
                ('img', models.FileField(upload_to='')),
                ('description', models.CharField(max_length=800)),
                ('location', models.CharField(max_length=500)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.RegisterModel')),
            ],
        ),
    ]
