# Generated by Django 3.0.5 on 2020-04-22 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='N_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
