# Generated by Django 3.0.5 on 2020-04-25 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_forwardedmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forwardedmodel',
            name='userd',
            field=models.BigIntegerField(max_length=50),
        ),
    ]
