# Generated by Django 3.0.5 on 2020-04-25 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20200425_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forwardedmodel',
            name='userd',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Post_Complaint'),
        ),
    ]
