# Generated by Django 3.0.5 on 2020-04-25 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20200425_1748'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('img', models.FileField(upload_to='')),
                ('description', models.CharField(max_length=800)),
                ('location', models.CharField(max_length=500)),
                ('date', models.DateTimeField(auto_now=True)),
                ('res_img', models.FileField(upload_to='')),
                ('res_des', models.CharField(max_length=800)),
                ('comp_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.ForwardedModel')),
            ],
        ),
    ]
