# Generated by Django 3.0.5 on 2020-04-27 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20200427_1645'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp_id', models.BigIntegerField(max_length=50)),
                ('category', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('img', models.FileField(upload_to='')),
                ('description', models.CharField(max_length=800)),
                ('location', models.CharField(max_length=500)),
                ('date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
